/*
=============================================================
  NORTHWIND DATABASE - Complete DDL Setup Script for Snowflake
=============================================================
  This script creates the full Northwind database with all
  tables, primary keys, and foreign key relationships.
  
  Run this script in any Snowflake account to recreate the
  Northwind database identically.
=============================================================
*/

-- Create the database and schema
CREATE OR REPLACE DATABASE NORTHWIND;
USE DATABASE NORTHWIND;
USE SCHEMA PUBLIC;

-- =====================
-- INDEPENDENT TABLES (no foreign key dependencies)
-- =====================

CREATE OR REPLACE TABLE CATEGORIES (
    CATEGORY_ID NUMBER(38,0) NOT NULL,
    CATEGORY_NAME VARCHAR(15) NOT NULL,
    DESCRIPTION VARCHAR(200),
    PRIMARY KEY (CATEGORY_ID)
);

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(5) NOT NULL,
    COMPANY_NAME VARCHAR(40) NOT NULL,
    CONTACT_NAME VARCHAR(30),
    CONTACT_TITLE VARCHAR(30),
    ADDRESS VARCHAR(60),
    CITY VARCHAR(15),
    REGION VARCHAR(15),
    POSTAL_CODE VARCHAR(10),
    COUNTRY VARCHAR(15),
    PHONE VARCHAR(24),
    FAX VARCHAR(24),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER(38,0) NOT NULL,
    LAST_NAME VARCHAR(20) NOT NULL,
    FIRST_NAME VARCHAR(10) NOT NULL,
    TITLE VARCHAR(30),
    TITLE_OF_COURTESY VARCHAR(25),
    BIRTH_DATE DATE,
    HIRE_DATE DATE,
    ADDRESS VARCHAR(60),
    CITY VARCHAR(15),
    REGION VARCHAR(15),
    POSTAL_CODE VARCHAR(10),
    COUNTRY VARCHAR(15),
    HOME_PHONE VARCHAR(24),
    EXTENSION VARCHAR(4),
    REPORTS_TO NUMBER(38,0),
    PRIMARY KEY (EMPLOYEE_ID)
);

CREATE OR REPLACE TABLE REGIONS (
    REGION_ID NUMBER(38,0) NOT NULL,
    REGION_DESCRIPTION VARCHAR(50) NOT NULL,
    PRIMARY KEY (REGION_ID)
);

CREATE OR REPLACE TABLE SHIPPERS (
    SHIPPER_ID NUMBER(38,0) NOT NULL,
    COMPANY_NAME VARCHAR(40) NOT NULL,
    PHONE VARCHAR(24),
    PRIMARY KEY (SHIPPER_ID)
);

CREATE OR REPLACE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER(38,0) NOT NULL,
    COMPANY_NAME VARCHAR(40) NOT NULL,
    CONTACT_NAME VARCHAR(30),
    CONTACT_TITLE VARCHAR(30),
    ADDRESS VARCHAR(60),
    CITY VARCHAR(15),
    REGION VARCHAR(15),
    POSTAL_CODE VARCHAR(10),
    COUNTRY VARCHAR(15),
    PHONE VARCHAR(24),
    FAX VARCHAR(24),
    HOMEPAGE VARCHAR(200),
    PRIMARY KEY (SUPPLIER_ID)
);

-- =====================
-- TABLES WITH SINGLE FOREIGN KEY DEPENDENCIES
-- =====================

CREATE OR REPLACE TABLE TERRITORIES (
    TERRITORY_ID VARCHAR(20) NOT NULL,
    TERRITORY_DESCRIPTION VARCHAR(50) NOT NULL,
    REGION_ID NUMBER(38,0),
    PRIMARY KEY (TERRITORY_ID),
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    PRODUCT_NAME VARCHAR(40) NOT NULL,
    SUPPLIER_ID NUMBER(38,0),
    CATEGORY_ID NUMBER(38,0),
    QUANTITY_PER_UNIT VARCHAR(20),
    UNIT_PRICE NUMBER(10,2),
    UNITS_IN_STOCK NUMBER(38,0),
    UNITS_ON_ORDER NUMBER(38,0),
    REORDER_LEVEL NUMBER(38,0),
    DISCONTINUED NUMBER(38,0) DEFAULT 0,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID VARCHAR(5),
    EMPLOYEE_ID NUMBER(38,0),
    ORDER_DATE DATE,
    REQUIRED_DATE DATE,
    SHIPPED_DATE DATE,
    SHIP_VIA NUMBER(38,0),
    FREIGHT NUMBER(10,2),
    SHIP_NAME VARCHAR(40),
    SHIP_ADDRESS VARCHAR(60),
    SHIP_CITY VARCHAR(15),
    SHIP_REGION VARCHAR(15),
    SHIP_POSTAL_CODE VARCHAR(10),
    SHIP_COUNTRY VARCHAR(15),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (SHIP_VIA) REFERENCES SHIPPERS(SHIPPER_ID)
);

-- =====================
-- TABLES WITH MULTIPLE FOREIGN KEY DEPENDENCIES
-- =====================

CREATE OR REPLACE TABLE ORDER_DETAILS (
    ORDER_ID NUMBER(38,0) NOT NULL,
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    UNIT_PRICE NUMBER(10,2) NOT NULL,
    QUANTITY NUMBER(38,0) NOT NULL,
    DISCOUNT NUMBER(4,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE OR REPLACE TABLE EMPLOYEE_TERRITORIES (
    EMPLOYEE_ID NUMBER(38,0) NOT NULL,
    TERRITORY_ID VARCHAR(20) NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID, TERRITORY_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (TERRITORY_ID) REFERENCES TERRITORIES(TERRITORY_ID)
);
